"use strict";
exports.__esModule = true;
var WhetherData_1 = require("./WhetherData");
var WhetherData_2 = require("./WhetherData");
var wd = new WhetherData_1.WhetherData();
var display = new WhetherData_2.StatisticsDisplay();
wd.addObserver(display);
wd.setMeasurements(3, 0.7, 760);
wd.setMeasurements(4, 0.8, 761);
wd.removeObserver(display);
wd.setMeasurements(10, 0.8, 761);
wd.setMeasurements(-10, 0.8, 761);
